name: aws-deploy


on:
  workflow_dispatch:
    branches:
        - main
        - feature
  push:
    branches:
        - main
        - feature

jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16.x'

      # - name: Set up Python
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: "3.9"

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip

      # - name: newman install
      #   run: sudo npm install -g newman

      # - name: Exec API_Test_Helper
      #   run: |
      #     python ./test/api_test_helper.py

      # - name: E2E Tests
      #   run: newman run ./GitHubActionsPostman.postman_collection.json

      # - name: Cleanup
      #   run: |
      #     rm -f ./GitHubActionsPostman.postman_collection.json
