name: aws-deploy


on:
  workflow_dispatch:
    branches:
        - main
  push:
    branches:
        - main
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: newman install
        run: sudo npm install -g newman

      - name: E2E Tests
        run: newman run ./GitHubActionsPostman.postman_collection.json
