name: aws-hello


on:
  workflow_call:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: print
        run: echo ${{ secrets.SAMPLE }}
