name: aws-hello2


on:
  workflow_run:
    workflows:
      - aws-deploy
    types:
      - completed

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

