name: aws-hello


on:
  workflow_run:
    workflows: ["aws-deploy"]
    types:
      - completed

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: hello
        uses: echo "Hello World"
