name: aws-hello


on:
  workflow_dispatch:
    branches:
        - main
  push:
    branches:
        - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

